version: '3.8'

services:
  app:
    container_name: laravel_app
    image: php:8.2
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "1234:1234"
    environment:
      - PHP_EXTENSIONS=dom xml
    command: php artisan serve --host=0.0.0.0 --port=1234
